TOPU-25 WIP: Add validation logic
Topu-project/backend_java pull request #10
Opened 2024-09-14 16:45 UTC by chans27

도중커밋

2024-09-22 06:39 UTC, falsystack requested changes

2024-09-22 06:39 UTC, falsystack commented on src/main/resources/messages.properties
> +recruitment.validation.notBlank.content=\uB0B4\uC6A9\uC744 \uC785\uB825\uD574 \uC8FC\uC138\uC694.
@chans27 
파일 저장이 `utf-8` 로 안되고 있는것 같네요 확인 부탁드릴게요

2024-09-22 06:39 UTC, falsystack commented on src/main/resources/application-local.properties
> +spring.messages.fallback-to-system-locale=false
@chans27 
[messages.properties](https://github.com/Topu-project/backend_java/pull/10/files#diff-0771b708161a9fbc2a5e9a05637222f39afce6e028cd010abcbaaaee1ade7653) 의 코멘트 드린 설정을 보고 필요할지 안필요할지 알것같아요

spring.messages.encoding=UTF-8 이건 있어도 좋을것 같아요

2024-09-22 06:39 UTC, falsystack commented on src/test/java/jp/co/topucomunity/backend_java/recruitments/controller/RecruitmentsControllerTest.java
> +    }
@chans27 
👍

하나만 입력하지 않았을 때의 테스트 케이스도 있으면 좋을것 같아요! 그 경우에도 `"모든 항목을 입력해야 합니다."` 가 표시되는 걸까요?

2024-09-22 06:39 UTC, falsystack commented on src/main/java/jp/co/topucomunity/backend_java/recruitments/controller/ExceptionController.java
> +        String errorMessage = messageSource.getMessage(e.getMessage(), null, request.getLocale());
@chans27 
에외에 정의되어 있는 에러코드를 가져오게 바꾸셨으니 메서드명도 문맥에 맞게 수정해주시면 좋을것 같아요
또는 
(밑에 내용은 대응안하셔도되용. 옵션입니다. )
`RecruitmentException` 에 추상 메서드로 `String getErrorCode()` 를 정의하시고 상속하는 모든 예외들이 구현해서 사용하는 곳에서는 `e.getErrorCdoe()` 해도 좋겠다는 생각이 들었습니다.

2024-09-22 06:39 UTC, falsystack commented on src/main/java/jp/co/topucomunity/backend_java/recruitments/controller/RecruitmentsController.java
> +    public void createRecruitment(@RequestBody @Valid CreateRecruitmentRequest request) { // TODO : バリデーション
@chans27 
`// TODO : バリデーション` 삭제 부탁드릴게요

2024-09-22 06:39 UTC, falsystack commented on src/main/java/jp/co/topucomunity/backend_java/recruitments/controller/out/RecruitmentErrorResponse.java
> + *   "validationErrors: {
👍

2024-09-22 06:39 UTC, falsystack commented on src/main/resources/messages.properties
> +
@chans27 
저희 프로젝트가 다국어 지원을 하지는 않으니 `messages.properties` 에 에러메시지를 정의해도 문제 없다고 생각하나 
에러메시지들의 경우 `errors.properties`에 넣었으면 좋겠다고 생각했습니다. 어떠신가요?

에러메세지의 프로퍼티명에 대한 제 의견은 
- validation은 중복되니 없어도 될꺼라고 생각되었습니다. (`errors.properties`에 넣었을 경우)
- notNull의 경우 공통메시지로 충분하다고 생각했습니다. (문제가 되는 필드의 이름도 같이 보내고 있기 때문)

2024-09-22 06:39 UTC, falsystack commented on src/main/java/jp/co/topucomunity/backend_java/recruitments/controller/in/UpdateRecruitmentRequest.java
> +    private Integer numberOfPeople;
@chans27 
`0` 이상인가에 대한 검증도 필요하다고 생각되었습니다

- `CreateRecruitmentRequest` も同様

2024-09-22 06:39 UTC, falsystack commented on src/main/java/jp/co/topucomunity/backend_java/recruitments/controller/in/UpdateRecruitmentRequest.java
> +    private Integer progressPeriod;
@chans27 
`0` 이상인가에 대한 검증도 필요하다고 생각되었습니다

2024-09-22 06:39 UTC, falsystack commented on src/main/java/jp/co/topucomunity/backend_java/recruitments/controller/in/UpdateRecruitmentRequest.java
> +    @NotNull(message = "{recruitment.validation.notNull.deadline}")
@chans27 
오늘 이후의 날짜인지 (과거의 날짜가 아닌지) 에 대한 검증도 필요하다고 생각되었습니다.

2024-09-22 16:18 UTC, chans27 commented on src/test/java/jp/co/topucomunity/backend_java/recruitments/controller/RecruitmentsControllerTest.java
> +    }
게더에서 얘기했을때 errors.properties의 내용을 세분화 하는게 좋다고 이야기했었는데, notNull은 굳이 세분화 할 필요 없다고 생각이 바뀌었습니다..ㅎㅎ (세분화 하지 않는게 화면쪽에서 더 깔끔하게 보일것 같아서..)

그렇기 때문에 전체 항목에 대해 notNull검증을 하나의 테스트케이스에서 하고,  notNull 이외의 검증(@Email, @FutureOrPresent @Min)만 나누어서 테스트케이스를 추가했습니다.

![스크린샷 2024-09-23 오전 1 13 26](https://github.com/user-attachments/assets/234cbc90-4cb2-40f0-8ffa-9b0469d4ccf4)

검증에 실패했을 때 errorMessage에는 `잘못된 요청입니다.` 가 들어오도록 수정했습니다.

2024-09-22 16:23 UTC, chans27 commented on src/main/resources/messages.properties
> +
맞는 말씀이신것 같습니다. 현재 정의하고 있는 내용들은 에러에 관한 내용들이므로 errors.properties로 파일명을 수정하고,
메세지의 프로퍼티명을 좀 더 간략화 해 보았습니다!

2024-09-22 16:35 UTC, chans27 commented on src/main/java/jp/co/topucomunity/backend_java/recruitments/controller/ExceptionController.java
> +        String errorMessage = messageSource.getMessage(e.getMessage(), null, request.getLocale());
메서드명을 `recruitmentNotFoundHandler`로 수정하고, @ExceptionHandler의 클래스를 
RecruitmentException 에서 RecruitmentException을 상속하는 RecruitmentNotFoundException로 수정했습니다!

2024-09-22 18:11 UTC, chans27 commented on src/main/java/jp/co/topucomunity/backend_java/recruitments/controller/in/UpdateRecruitmentRequest.java
> +    @NotNull(message = "{recruitment.validation.notNull.deadline}")
@FutureOrPresent 어노테이션으로 날짜 검증 추가했습니다!

2024-09-25 14:55 UTC, falsystack approved these changes
LGTM!

2024-09-25 14:55 UTC, falsystack commented on src/test/java/jp/co/topucomunity/backend_java/recruitments/controller/RecruitmentsControllerTest.java
> +                .andExpect(jsonPath("$.errorMessage").value("잘못된 요청입니다."))
@chans27 
(대응 하실지는 예찬씨가 결정해주세요)
`status()` 검증도 있었으면 보다 좋을것 같다고 생각했습니다.

2024-09-25 14:55 UTC, falsystack commented on src/main/java/jp/co/topucomunity/backend_java/recruitments/controller/in/UpdateRecruitmentRequest.java
> +    private Integer progressPeriod;
@chans27 
(대응 하실지는 예찬씨가 결정해주세요)
`0` 이상인지에 대한 최솟값만 검증한다면 `@Min` 이 어울리지 않을까 생각했습니다.

2024-09-25 14:55 UTC, falsystack commented on src/main/java/jp/co/topucomunity/backend_java/recruitments/controller/in/UpdateRecruitmentRequest.java
> +    private Integer numberOfPeople;
@chans27 
(대응 하실지는 예찬씨가 결정해주세요)
`0` 이상인지에 대한 최솟값만 검증한다면 `@Min` 이 어울리지 않을까 생각했습니다.

2024-09-25 14:55 UTC, falsystack commented on src/main/java/jp/co/topucomunity/backend_java/recruitments/controller/ExceptionController.java
> +        String errorMessage = messageSource.getMessage(e.getMessage(), null, request.getLocale());
@chans27 
(대응 하실지는 예찬씨가 결정해주세요)
현재 예외를 중앙집중적으로 핸들링하고 있어서 현재 지정되어 있는 예외 이외의 예외의 경우 여기서 먹어버릴 가능성이 있다고 생각했습니다.
- `RecruitmentNotFoundException`, `MethodArgumentNotValidException` 이외의 예외들

적고나서 생각해보니 지금 티켓이 아닌 다른 티켓에서 대응하는게 더 좋을것 같네용

2024-09-26 13:38 UTC, chans27 commented on src/main/java/jp/co/topucomunity/backend_java/recruitments/controller/in/UpdateRecruitmentRequest.java
> +    private Integer progressPeriod;
말씀하신대로 0이상만 검증한다면 @Min도 좋을것같은데, @Range여도 기능상 큰 차이가 없는점, 혹~~~시나 나중에 max값을 지정해 줄 필요성이 있으니 이대로 냅둬도 될것같습니다!

2024-09-26 13:40 UTC, chans27 commented on src/test/java/jp/co/topucomunity/backend_java/recruitments/controller/RecruitmentsControllerTest.java
> +                .andExpect(jsonPath("$.errorMessage").value("잘못된 요청입니다."))
동의합니다 ㅎㅎ 넣는게 정확할것같습니다 추가하겠습니다!

2024-09-26 13:50 UTC, chans27 commented on src/main/java/jp/co/topucomunity/backend_java/recruitments/controller/in/UpdateRecruitmentRequest.java
> +    private Integer numberOfPeople;
아래 설명과 같습니다~~

2024-09-26 15:19 UTC, falsystack approved these changes
룩굿투미!

2024-09-27 13:36 UTC, merged